"use client";
import React, { useState } from "react";


const QuestionPage = () => {
  const faqs = [
    {
      question: "How do I start an interview?",
      answer:
        "Once you log in and access the dashboard, you can create a new interview by providing details such as the job role, required skills, and years of experience. After filling out the information, simply click on the 'Start Interview' button to begin the session.",
    },
    {
      question: "How are the interview questions generated?",
      answer:
        "The interview questions are generated by Google Gemini AI, which creates personalized questions based on the job role, skills, and experience level you specify during the interview setup.",
    },
    {
      question: "How do I answer the interview questions?",
      answer:
        "You can answer the interview questions by speaking. The system will record your responses, and after each question, you can proceed to the next one. Once all questions are answered, click on the 'End Interview' button to finish.",
    },
    {
      question: "How is feedback provided after the interview?",
      answer:
        "After completing the interview, AI-generated feedback will be provided based on your answers. You can also see a rating that reflects your performance during the interview.",
    },
    {
      question: "Can I view all my past interviews?",
      answer:
        "Yes, all your past interviews are saved and can be accessed from the dashboard. You can view the feedback and ratings for each interview session.",
    },
    {
      question: "How long does an interview session last?",
      answer:
        "The duration of an interview session depends on the number of questions generated by the AI and how long you take to answer each one. Typically, each session lasts between 15 to 30 minutes.",
    },
    {
      question: "Can I take the interview multiple times?",
      answer:
        "Yes, you can take the interview as many times as you want. Each time, the AI will generate new questions based on your input for job role, skills, and experience.",
    },
    {
      question: "Is there a time limit for answering each question?",
      answer:
        "No, there is no time limit for answering each question. You can take your time to respond, but it’s advisable to keep your answers concise and focused.",
    },
    {
      question: "Can I get feedback on specific questions from the interview?",
      answer:
        "Currently, feedback is provided for the entire interview session. However, you can review the AI-generated feedback and improve your responses for future interviews.",
    },
    {
      question: "How accurate is the AI-generated feedback?",
      answer:
        "The AI-generated feedback is based on your answers and aims to provide constructive suggestions. While it is designed to help you improve, it is always a good idea to review the feedback and practice further.",
    },
    {
      question: "Can I share my interview results with others?",
      answer:
        "Yes, you can share your interview results, including feedback and ratings, by downloading your report or taking a screenshot.",
    },
    {
      question: "What happens if I get interrupted during the interview?",
      answer:
        "If you get interrupted, you can resume the interview as long as you click on the 'Start Interview' button again. You may need to answer any remaining questions after the interruption.",
    },
    {
      question: "Is there a mobile app available for this service?",
      answer:
        "Currently, this service is available via the website. A mobile app may be developed in the future, and updates will be posted on our website.",
    },
    {
      question: "Can I change the job role and skill set after starting the interview?",
      answer:
        "No, once you’ve started the interview, the job role and skill set cannot be changed. You would need to create a new interview with the desired changes.",
    },
    {
      question: "What is the purpose of the 'Reset Progress' feature in the dashboard?",
      answer:
        "The 'Reset Progress' feature allows you to clear your interview history and start over if you want to retake interviews without previous feedback influencing your performance.",
    },
    {
      question: "Can I customize the interview questions?",
      answer:
        "Currently, the interview questions are automatically generated by the AI based on the job role, skills, and experience you select. Customization of questions is not available at the moment, but we’re working on future enhancements.",
    },
    {
      question: "What should I do if I face technical issues during the interview?",
      answer:
        "If you face technical issues, you can contact our support team through the 'Help' section on the website. They’ll assist you in resolving any issues you encounter.",
    },
    {
      question: "Can I take the interview in multiple sessions?",
      answer:
        "Interviews must be completed in a single session to receive feedback. However, you can take the interview multiple times if needed.",
    },
    {
      question: "How do I improve my interview performance based on the feedback?",
      answer:
        "The feedback provides areas where you can improve, including communication skills, confidence, and the quality of your answers. Use the feedback to practice and refine your answers for future interviews.",
    },
    {
      question: "Can I track my interview progress over time?",
      answer:
        "Yes, you can track your progress by reviewing your past interviews and feedback from your dashboard. This allows you to see how you’re improving over time.",
    },
  ];
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div
      className="min-h-screen flex flex-col items-center py-10 px-4"
      style={{
        backgroundImage: "url('/1.jpg')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
      }}
    >
      <h1 className="text-4xl font-bold text-gray-800 mb-8 bg-white bg-opacity-80 px-4 py-2 rounded-lg">
        Frequently Asked Questions
      </h1>
      <div className="w-full max-w-2xl bg-white bg-opacity-90 p-6 rounded-lg shadow-lg">
        {faqs.map((faq, index) => (
          <div key={index} className="mb-4">
            <button
              onClick={() => toggleFAQ(index)}
              className="w-full flex justify-between items-center bg-gray-200 shadow-md rounded-lg p-4 text-left font-medium text-gray-800 hover:bg-gray-300 transition-all"
            >
              <span>{faq.question}</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className={`h-6 w-6 transform transition-transform ${
                  openIndex === index ? "rotate-180" : "rotate-0"
                }`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            {openIndex === index && (
              <div className="mt-2 bg-gray-50 p-4 rounded-lg text-gray-600">
                {faq.answer}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default QuestionPage;